all:
	cd Aufgabe1; make
	cd Aufgabe2; make
	cd Aufgabe3; make
	cd Aufgabe4; make
	
clean:
	cd Aufgabe1; rm -f *.o *.x
	cd Aufgabe2; rm -f *.o *.x
	cd Aufgabe3; rm -f *.o *.x
	cd Aufgabe4; rm -f *.o *.x